### ISSUE TITLE
Add eslint and prettier with lint-staged on pre-commit

### ISSUE THREAD

**Issue by jgcmarins** [gabrielreisn/react-todo-app#4]
### Example
- https://github.com/entria/ReactNavigationRelayModern/blob/master/package.json#L44
### References
- https://github.com/eslint/eslint
- https://github.com/prettier/prettier
- https://github.com/okonet/lint-staged

**Comment by gabrielreisn** [comment]
Ok, using some previous configuration (already added to package.json)
